package Chap13;

/****
 *      InputMisMatchException
 *
 *  WRITE A PROGRAM THAT PROMPTS THE USER TO READ IN 2 INTEGERS AND DISPLAY THEIRS SUM.
 *  YOUR PROGRAM SHOULD PROMPT THE USER TO READ THE NUMBER AGAIN IF THE INPUT IS INCORRECT
 *
 * */
public class InputMisMatchExcep {
}
